#!/usr/bin/env bash

# Silences alert, posting a note to the Pager Duty incident

# User ID of the silent test account
PD_SILENT_TEST_USER='P8QS6CC'

usage(){
  echo 'Silence an alert, posting a note to the PagerDuty incident'
  echo ''
  echo '  Accepts a PD incident number, and a quote-enclosed string'
  echo ''
  echo 'Usage'
  echo "  ${0} [options] [pagerduty_incident] [note]"
  echo ''
  echo 'Options'
  echo '  -h    Print help message'
  echo '  -f    Do not prompt for confirmation before silencing'
  echo ''
}

FORCE='FALSE'

while getopts ':hf' opt
do
  case ${opt} in
    h ) usage ; exit 0
      ;;
    f ) FORCE='TRUE'
      ;;
    \? ) echo -e "Unknown option: -${OPTARG}\n" ; usage ; exit 1
      ;;
  esac
done
shift $((OPTIND -1))

# Check required commands are in $PATH
if ! command -v pd > /dev/null
then
  echo -e "Command 'pd' is required for this script to work.\n"
  usage
  exit 1
fi

PD_ALERT="${1}"

# Note to add to the PD alert before silence and merge
PD_NOTE="${2}"

if [[ -z "${PD_ALERT}" ]] ;
then
  echo -e 'The "pagerduty_incident" argument is required\n'
  usage
  exit 1
fi

if [[ -z "${PD_NOTE}" ]] ;
then
  echo -e 'A PagerDuty note is required\n'
  usage
  exit 1
fi

set -o nounset

pd incident:ack -i ${PD_ALERT}
pd incident:notes -i ${PD_ALERT} -n "$PD_NOTE"
pd incident:assign -i ${PD_ALERT} -u $PD_SILENT_TEST_USER

